### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by c3p0vsr2d2** [knyar/alexa-exporter#1]
Hello, I am not able to get the script to work.

I am getting a 401 error back from the Amazon server.
Are the 2 cookies listed in the README the only ones that are needed?

I am not on the UK site, but accessing the (perhaps US centric) links:
https://alexa.amazon.com/api/phoenix
https://alexa.amazon.com/api/phoenix/group
etc

The two cookies I am looking at are:
at-main
ubid-main

TIA for any pointers.

**Comment by knyar** [comment]
Yeah the cookie names and URLs currently hardcoded in the script (and documented in README) are definitely UK-specific. If you are able to make this work for another regions, please submit a PR!

Based on [some sources](https://flows.nodered.org/node/node-red-contrib-alexa-remote2) you might want to try `pitangui.amazon.com` as the hostname for API endpoints in the US. Good luck!

**Comment by c3p0vsr2d2** [comment]
Hey knyar, looks like I am able to get it to work with the exact same two cookies I listed above, the same US-centric links above, and the original hostname/user-agent in your code.
I rewrote the code a bit to read data into an influxdb instance, and all is well with the world now.
Many thanks for the Alexa access in your code. 
I strongly feel this project could be used as a fantastic starting point for a HomeAssistant integration, there are [many](https://www.reddit.com/r/homeassistant/comments/v974l5/has_anyone_integrated_the_new_amazon_smart_air/) [many ](https://www.reddit.com/r/homeassistant/comments/quri9e/home_air_monitoring_suggestions/) folks asking for this for a while. I would have pursued this in a different life.
